name: gsettings
version: 0.0.1

description:
  GSettings client

homepage: https://github.com/canonical/gsettings.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dbus: ^0.5.0
  xdg_directories: ^0.2.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.16.8
